---
kind: pipeline
name: default
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
steps:
# - name: run
#   image: docker
#   volumes:
#   - name: dockersock
#     path: /var/run/docker.sock
#   commands:
#   - docker run --privileged --rm tonistiigi/binfmt --install all
# - name: dockerx
#   image: thegeeklab/drone-docker-buildx:20.10.14
#   privileged: true
#   settings:
#     experimental: true
#     auto_tag: true
#     platforms: 
#     - linux/arm/v7
#     username: rajiteh
#     password:
#       from_secret: gitlab_token
#     repo: registry.gitlab.com/rajiteh/orca_containers
#     registry: registry.gitlab.com
#     auto_tag_suffix: pi-screen-remote
- name: helm-deploy
  image: alpine/helm:3.8.0
  secrets: [orca_k3s_kubeconfig_b64]
  environment:
    KUBECONFIG: /tmp/kubeconfig.yaml
    ORCA_K3S_KUBECONFIG_B64:
      from_secret: orca_k3s_kubeconfig_b64
  commands:
    - echo "${ORCA_K3S_KUBECONFIG_B64}" | base64 -d > ${KUBECONFIG}
    - helm upgrade pi-screen-remote --install --create-namespace --namespace ls90-pi-screen-remote --debug chart/pi-screen-remote
- name: deployment-rollout
  image: bitnami/kubectl:1.22.7
  secrets: [orca_k3s_kubeconfig_b64]
  environment:
    KUBECONFIG: /tmp/kubeconfig.yaml
    ORCA_K3S_KUBECONFIG_B64:
      from_secret: orca_k3s_kubeconfig_b64
  commands:
    - echo "${ORCA_K3S_KUBECONFIG_B64}" | base64 -d > ${KUBECONFIG}
    - kubectl rollout restart --namespace ls90-pi-screen-remote deployment pi-screen-remote
